apiVersion: v1
kind: Service
metadata:
  name: k8s-read
  labels:
    app: k8s-read
    version: latest
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6100
    targetPort: http
    protocol: TCP
  selector:
    app: k8s-read
