kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-read-role-binding
subjects:
  - kind: ServiceAccount
    name: kube-api-reader
roleRef:
  kind: Role
  name: kube-read-role
  apiGroup: rbac.authorization.k8s.io
